# This workflow orchestrates the deployment of a Flutter web application to multiple
# environments of Cloudflare Pages. The goal is to test the application with different
# build configurations to choose the best one for the production deployment.
name: Deploy Flutter web app to multiple deployment environments in Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  HTML-Canvaskit:
    uses: ./.github/workflows/deploy_flutter_web_to_cloudflare.yml
    with:
      buildRenderer: canvaskit
      deploymentBranch: canvaskit
    secrets: inherit

  Wasm:
    uses: ./.github/workflows/deploy_flutter_web_to_cloudflare.yml
    with:
      buildRenderer: wasm
      deploymentBranch: main
    secrets: inherit
